; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

board_build.partitions = partitions/partitions.csv

build_flags =
    -DCONFIG_BT_BLE_ENABLED=1
    -DCONFIG_BT_BLUEDROID_ENABLED=1
    -DCONFIG_BT_BLE_50_FEATURES_SUPPORTED=0
    -DCONFIG_BT_BLE_42_FEATURES_SUPPORTED=1
    -DIDF_MAINTAINER=1
    -D CONFIG_FATFS_LFN_HEAP=1
    -D CONFIG_FATFS_MAX_LFN=255

lib_deps =
    git@github.com:SenseAI-Organization/construct-library.git#dev
    git@github.com:SenseAI-Organization/component-library.git#dev
    git@github.com:SenseAI-Organization/core-library.git#dev
    git@github.com:SenseAI-Organization/proto-firmware-pj.git